[package]
name = "Milk-Backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
envconfig = "0.11.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.1"
env_logger = "0.11.6"
