services:
  backend:
    build: ./Milk-Backend
    ports:
      - "5050:5050"
    env_file:
      - Milk-Backend/.env

  webview:
    build: ./Milk-WebView
    ports:
      #TODO: Before deploying, do the port fowarding
      - "5173:5173"
    env_file:
      #I didn't find a practical way of symlinking the env_variables dir while in the container
      - Milk-WebView/.env
    depends_on:
      - backend


networks:
  milk-network:
    driver: bridge
  
volumes:
  db:
