name: deploy-to-vps

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      WEBVIEW_PORT: ${{ secrets.WEBVIEW_PORT }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
      WEBVIEW_URL: ${{ secrets.WEBVIEW_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: create .env file
        run: |
          echo "BACKEND_PORT=${BACKEND_PORT}" >> .env
          echo "WEBVIEW_PORT=${WEBVIEW_PORT}" >> .env
          echo "VITE_BACKEND_URL=${VITE_BACKEND_URL}" >> .env
          echo "BACKEND_HOST=${BACKEND_HOST}" >> .env
          echo "WEBVIEW_URL=${WEBVIEW_URL}" >> .env

      - name: Build Docker images
        run: docker compose build

      - name: Save images as tarballs
        run: |
          docker compose config --services | xargs -I{} docker compose images -q {} | xargs -r docker save -o images.tar

      - name: Setting up keys
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.vps_host }} >> ~/.ssh/known_hosts

          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.VPS_SSH_KEY }}"

          echo "${{ secrets.VPS_SSH_KEY }}" > ${HOME}/.ssh/milk_key.pem
          chmod 400 ${HOME}/.ssh/milk_key.pem


      - name: Install rsync and Transfer files using rsync
        run: |
          # Rsync command to transfer files
          rsync -avz -e "ssh -i ${HOME}/.ssh/milk_key.pem" images.tar compose.yml .env ${{ secrets.VPS_USER }}@${{ secrets.vps_host }}:~/Milk-Folio/


      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd Milk-Folio/
            docker load -i images.tar
            docker-compose down
            docker-compose up --build -d
